version: '3'
services:
  fast-api-app:
    container_name: "fast-api-app"
    build: .
    tty: true
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    ports:
      - 8000:8000  # ホストマシンのポート8000を、docker内のポート8000に接続する

  fast-api-db:
    container_name: "fast-api-db"
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes' # rootアカウントをパスワード無しで作成
      MYSQL_DATABASE: 'demo' # 初期データベース
      TZ: 'Asia/Tokyo'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 33306:3306 #ホストのポート33306を、dockerのポート3306に繋げる

volumes:
      mysql_data:
