version: '3'
services:
  demo-app:
    container_name: "demo-app"
    build: .
    tty: true
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    ports:
      - 8000:8000  # ホストマシンのポート8000を、docker内のポート8000に接続する
