version: '3'
services:
  fast-api-app:
    container_name: fast-api-app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    tty: true
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    command: uvicorn api.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000  # ホストマシンのポート8000を、docker内のポート8000に接続する

  fast-api-mysql:
    container_name: "fast-api-mysql"
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes' # rootアカウントをパスワード無しで作成
      MYSQL_DATABASE: 'demo'
      TZ: 'Asia/Tokyo'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - 'mysql_data:/var/lib/mysql'
      - './mysql/etc/my.cnf:/etc/my.cnf'
    ports:
      - 33306:3306

volumes:
  mysql_data:
